name: Deploy Production

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    environment: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/project-hackathon-codecon26/toilet-kpi/backend

            git pull origin main

            docker build -t toilet-kpi-backend:new .
                    
            docker rm -f toilet-kpi-backend 2>/dev/null || true
                    
            docker tag toilet-kpi-backend:new toilet-kpi-backend:latest
                    
            docker run -d \
              --name toilet-kpi-backend \
              -p 3001:3001 \
              toilet-kpi-backend:latest